### ISSUE TITLE
Alignment of release binaries platforms

### ISSUE THREAD

**Issue by sabre1041** [uor-framework/uor-client-go#40]
**What is the problem you're trying to solve**

The current release process only produces binaries for amd64 linux and osx. Align release with multi arch binaries in #39 

**Describe the solution you'd like**
Update goreleaser to account for additional binary targets

**Comment by usrbinkat** [comment]
Attempted to solve this on my fork [HERE](https://github.com/usrbinkat/uor-client/blob/buildx/.goreleaser.yaml), the amd64 build works flawlessly, but my arm64 build is failing to find the binary when copying into the container during container build.

**Comment by usrbinkat** [comment]
Propose building and pushing:
  - [ ] binaries:
    - [ ] Linux:
      - [ ] arm64
      - [ ] amd64
      - [ ] s390x
      - [ ] ppc64le
    - [ ] Darwin:
      - [ ] arm64
      - [ ] amd64
    - [ ] Windows:
      - [ ] amd64
  - [ ] Containers:
    - [ ] Linux:
      - [ ] arm64
      - [ ] amd64
  - [ ] SBOM
  - [ ] Checksum artifacts
