### ISSUE TITLE
[SPIKE] Investigate Virtual Filesystem Options for UOR Object Store

### ISSUE THREAD

**Issue by afflom** [uor-framework/uor-client-go#81]
**What is the problem you're trying to solve**
Existing applications (Applications that rely on location addressing) will need a compatibility layer when interacting with UOR Collections. 

**Describe the solution you'd like**
A virtual filesystem can be used to provide a compatibility layer to clients that reference filesystem locations. The virtual filesystem would provide transparent access to UOR Collection content from calling applications making location addressing.

**Comment by jpower432** [comment]
Closing this. The repo has been created in the `uor-commnunity` org at https://github.com/uor-community/uor-fuse-go
